version: '3.8'

services:  
  create-pet:
    build:
      context: ./create-pet
    image: joeli2104/create-pet:latest
    ports:
      - "3001:3001"
    networks:
      - pet_network

  update-pet:
    build:
      context: ./update-pet
    image: joeli2104/update-pet:latest
    ports:
      - "3002:3002"
    networks:
      - pet_network

  get-pet-by-id:
    build:
      context: ./get-pet-by-id
    image: joeli2104/get-pet-by-id:latest
    ports:
      - "3003:3003"
    networks:
      - pet_network

  get-all-pets:
    build:
      context: ./get-all-pets
    image: joeli2104/get-all-pets:latest
    ports:
      - "3004:3004"
    networks:
      - pet_network

  delete-pet:
    build:
      context: ./delete-pet
    image: joeli2104/delete-pet:latest
    ports:
      - "3005:3005"
    networks:
      - pet_network

networks:
  pet_network:
    driver: bridge
